### ISSUE TITLE
Sanity check the one-hot encoder

### ISSUE THREAD

**Issue by ccurtis7** [pmont056/62k-crystals#11]
Do the following:

* Manually calculate the output of 1-2 molecules, then compare what your code gives you.
* Run your one-hot encoder on 10 molecules from the original paper.
* Run your one-hot encode on 10 molecules from the 62k dataset.

**Comment by mpham26uchicago** [comment]
1. Sanity Check Good everything except Chirality. calc_atom_feature ok!
2. Preprocessing finished. How do I save the preprocessed list so I don't repeat it every time I run the code?
![image](https://user-images.githubusercontent.com/61213567/80297707-a0920b00-873a-11ea-9831-21f432a47e67.png)

3. Max length: 281
![image](https://user-images.githubusercontent.com/61213567/80297729-d0411300-873a-11ea-81ce-1fb359f0b47a.png)

@ccurtis7

**Comment by ccurtis7** [comment]
@pmont056 You could save the file using a reading and writing method like [this](https://stackabuse.com/reading-and-writing-lists-to-a-file-in-python/), although I don't know how much time it would save you. You could time both to see if there is any significant differences in time saved to read the data in from a text file versus re-running the for loop.
