### ISSUE TITLE
Fill array doesn't work for some reasons

### ISSUE THREAD

**Issue by mpham26uchicago** [pmont056/62k-crystals#12]
I try to follow what you did yesterday. I ran your example and it worked. However, when I put it in the function it doesn't work for some reason. I check all the other functions. There were some minor bugs but I fixed them. It seems like the only thing that didn't work is filling in the empty array. Everything before that functions as I expected. The code is in the 62k folder, filename OHE_problems.py. I think the problem is on line 200 and 205. @ccurtis7

**Comment by ccurtis7** [comment]
@pmont056, when I run your wrapper function `one_hot_encoder`, it errors out here. It doesn't seem that you have defined the label object in `calc_structure_feature` from what I can tell.

https://github.com/pmont056/62k-crystals/blob/45849d2e366350ce11d2a51bb0500b76f93070ac/sixty2k_crystals/OHE_problems.py#L161-L167

**Comment by ccurtis7** [comment]
Here is the error message:

![image](https://user-images.githubusercontent.com/16652719/80608797-2b4d6100-89ec-11ea-9408-94ffbd927d7f.png)

**Comment by mpham26uchicago** [comment]
> Here is the error message:
> 
> ![image](https://user-images.githubusercontent.com/16652719/80608797-2b4d6100-89ec-11ea-9408-94ffbd927d7f.png)

label = []      # Label fixed taken directly from paper

This is how you would fix this problem. Just add this at the beginning of the code and I think everything should run

**Comment by mpham26uchicago** [comment]
It turned out there wasn't a problem in the first place. I just didn't know how to check for the answer. But there is another little problem. For example, when I put Cl in, for example, it would generate an array for Cl. But then, because it split the Cl into 2, it would create a blank array for "l" ("l" as in lizard). I look up this problem and it seems like we have to go with a while loop. Do you want to switch to this approach instead? @ccurtis7

**Comment by mpham26uchicago** [comment]
![image](https://user-images.githubusercontent.com/61213567/80783665-555b6c00-8b2f-11ea-95e8-947188374d67.png)
This is when the function analyses "l" as in lizard. It correctly returns an empty array but we don't want this.
