### ISSUE TITLE
One Hot Encode "For" loop doesn't work

### ISSUE THREAD

**Issue by mpham26uchicago** [pmont056/62k-crystals#13]
While I was running my code, I found out that there are some problems with the datasets we are trying to use. I test the first 5000 molecules and I found out there are 34 incompatible smiles string. Extrapolate from the data set there would be about 415 errors like this. In this case, do you want to just take them out and continue from there? It's only 0.7 % of the data so I think we could live with that. 

The usual error looks something like this
![image](https://user-images.githubusercontent.com/61213567/80895048-8eadec00-8c95-11ea-89d9-919e6d659a40.png)

Or sometimes it's like this 
![image](https://user-images.githubusercontent.com/61213567/80895099-f2381980-8c95-11ea-8a3c-cd598430ca6f.png)

I think I'm going to write some code that's going to ignore the errors and this way it can count up everything faster. Up until this point, I just compile the number of errors manually and this is really consuming. The next step would probably be to remove the errors and hopefully every else should be fine. @ccurtis7

**Comment by mpham26uchicago** [comment]
I generate the list for all the incompatible molecules. There are 454 of them in total.

![image](https://user-images.githubusercontent.com/61213567/80896096-88bd0880-8c9f-11ea-8d81-a78948a5e063.png)

I put all the index into a list so I can use it to erase these strings later.

**Comment by ccurtis7** [comment]
@pmont056 That's fine in my book!
