### ISSUE TITLE
Compile 3D OHE array

### ISSUE THREAD

**Issue by mpham26uchicago** [pmont056/62k-crystals#14]
The next step is to put everything together into one hot encode array. I did this by creating an empty nparray and filling in everything using a for loop. This is then saved because the code takes quite a while to run.

![image](https://user-images.githubusercontent.com/61213567/80922959-5cec6200-8d35-11ea-8a6b-c0691e43a0f6.png)

About 11 minutes is a good estimate. I found this out by extrapolating the time it takes to run 2000 molecules to 62k. I would have expected it to be much longer.

![image](https://user-images.githubusercontent.com/61213567/80923000-991fc280-8d35-11ea-92c1-9a96ac456b1d.png)

This is the code for future reference.

![image](https://user-images.githubusercontent.com/61213567/80923021-c66c7080-8d35-11ea-8af3-6c3f30af557a.png)

**Comment by mpham26uchicago** [comment]
The code ran very well and it takes 18 minutes in total because I added some indicator code in to tell me of the progress of the code. I test the accuracy over the different molecules, Heavy atoms, Hydrogen, and structural characteristics. Everything turns works out in the end. The final shape is (42, 281, 61489) which matches the expected dimensions. The next step is to apply this to the CNN models. Hopefully, there wouldn't be any big problem.

**Comment by ccurtis7** [comment]
Great job @pmont056!
