### ISSUE TITLE
Building Smiles Model

### ISSUE THREAD

**Issue by mpham26uchicago** [pmont056/62k-crystals#15]
This model is the same as the paper using CNN.

However, there are some modifications coming from the fact that we don't have access to major GPU power. Therefore, we can't use the module cupy. However, we are just going to replace it with numpy. Documentation is on the file called "smiles_cnn". @ccurtis7

**Comment by mpham26uchicago** [comment]
There seems to be a problem when inputting the array into the cnn model. I suggest turning the array into images and then pass the images through the cnn.

It would look something like this.

You should try running the code for yourself, mind that you have to already process the molecules into One-Hot-Encode arrays. It's very aesthetic.

![image](https://user-images.githubusercontent.com/61213567/81369458-58160e00-90a7-11ea-96f5-352dbf5ede0d.png)

The result for molecule[1] looks something like this. The color is probably because there is decimal in the 1 hot encode array.

![image](https://user-images.githubusercontent.com/61213567/81369517-8267cb80-90a7-11ea-9a4f-4daf8790af09.png)

The dimension is 42 by 281, which is the expected dimension

**Comment by mpham26uchicago** [comment]
I discover 2 ways to turn the array into an image. Here's a summary of both methods.

**1. Using NumPy/PILLOW Image.fromarray function**
This takes the ohe array and turns it an RGB image. I'm not quite sure of the process they do this but every image seems to be filled with some combinations of red, green, blue, and sometimes purple. 

Running a for loop for this method on the complete datasets takes 20.9 seconds.

The image for the molecule 'Cc1ccc(cc1)S(=O)(=O)N[C@H](c1nnc(o1)SCc1ccc(cc1)Cl)C' looks something like this.

![image](https://user-images.githubusercontent.com/61213567/81433159-f7271e00-9118-11ea-931d-9c3cf1666019.png)

The dimension is correct with (42, 281)

The format of the image is "PIL.Image.Image".

Here's the code:

![image](https://user-images.githubusercontent.com/61213567/81434236-b4fedc00-911a-11ea-8c35-471fdf8a4bfd.png)

**2. Using matplotlib plt.imshow function**
This takes the ohe array and turns it a colored image(I'm not sure which type). However, using this method, the end result image is more organized and I think more clearly represented the 1s and 0s of the ohe array. This method, however, takes 175.1 seconds to process the entire dataset.

The image for the same molecule looks something like this.

![image](https://user-images.githubusercontent.com/61213567/81433533-8c2a1700-9119-11ea-84fd-a55a1fa2795d.png)

The dimension is correct with (42, 281)

The format of the image is "matplotlib.figure.Figure"

Here is the code:

![image](https://user-images.githubusercontent.com/61213567/81434274-c0520780-911a-11ea-9ebd-afe54f03b2af.png)

**Comment by ccurtis7** [comment]
You could try running the code through Google CoLab, as you can get free access to a GPU.

> However, there are some modifications coming from the fact that we don't have access to major GPU power. Therefore, we can't use the module cupy. However, we are just going to replace it with numpy. Documentation is on the file called "smiles_cnn". @ccurtis7

**Comment by ccurtis7** [comment]
Hmmmm, I don't think there is any need to "turn" it into an image, as a digital image at its core is just a matrix of pixel values. It is, in a sense, already an image. The `plt.imshow` function just displays the existing image, rather than actually modifying the data in any way.

At least for the matplotlib implementation, the default color scheme is, I believe, Viridis. High pixel values are coded as yellow, low pixel values as purple, and everthing in between in a variety of shades of greens and blues.

**Comment by mpham26uchicago** [comment]
I put their CNN model on Colab. I was also able to install cuda and cupy. 

I found the list of hyperparameters on their paper.
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2523-5/tables/2
![image](https://user-images.githubusercontent.com/61213567/81481738-02e11600-91e7-11ea-891b-97be7670fbcf.png)

There is just one little problem. For their model, their input window size is (maxlen, 42) in our case is (281, 42) instead of (42, 281). Do you think this difference comes from the one-hot encoding method or can we just do something to flip the number of the dimension? 

![image](https://user-images.githubusercontent.com/61213567/81481723-ecd35580-91e6-11ea-824f-9a4f1398c32f.png)

This is the summary

**Comment by mpham26uchicago** [comment]
Check out smiles_cnn for the edited code. I add some comments and define some hyperparameters. I'm only not sure what the hyperparameters "n_hid" (line 39) and "t" (line 85) do.  @ccurtis7

**Comment by ccurtis7** [comment]
Flipping the dimensions is fine-- it should align with the expected format n x p where n is the number of observations and p is the defined features.
