### ISSUE TITLE
New One Hot Encode 

### ISSUE THREAD

**Issue by mpham26uchicago** [pmont056/62k-crystals#9]
-Better Documented
-Similar Structure

**Comment by mpham26uchicago** [comment]
One hot encode aromatic

**Comment by mpham26uchicago** [comment]
Padding to 400

**Comment by mpham26uchicago** [comment]
Add vector for hydrogen

**Comment by ccurtis7** [comment]
@pmont056 implemented the one-hot encoder as specified in [the paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2523-5)

He's just working out a few bugs.
